### ISSUE TITLE
Struktur registered_users.txt

### ISSUE THREAD

**Issue by spinyB** [CaribbeanMax/FPP_WS_16-17#12]
@CaribbeanMax fällt dir Struktur zur Anordnung der Usernamen mit Passwort ein? Ich würde sonst Usernamen1#Passwort1
Usernamen2#Passwort2
usw.
schreiben. Wird ein zweites Trennzeichen gebraucht am Passwortende?

**Comment by spinyB** [comment]
Der FileReader kann zeilenweise lesen. substringBefore( "string", "char" ) und substringAfter(...) erstellt einen String vor bzw hinter einem Zeichen. Somit würde es passen.

**Comment by CaribbeanMax** [comment]
Jo 'EoL' (End of Line :P) ist ja auch nur ein Zeichen und wenns dann sogar extra Methoden dafür gibt umso besser

**Comment by spinyB** [comment]
**.closed**

Usernamen#Passwort
readline() zum zeilenweise Einlesen
substringBefore() & substringAfter() um Name und Passwort auszulesen
