### ISSUE TITLE
2 Issues in table class

### ISSUE THREAD

**Issue by spinyB** [CaribbeanMax/FPP_WS_16-17#7]
@CaribbeanMax 
- line 94: erkennt Main.inputBlindRaise nicht, ich schätze mal du musst Main.java updaten(methode inputBlindRaise ist in Main.java nicht drin)
- line 104: inputStartMoney(String, int) Aufruf, jedoch in Main.java nur mit (String) deklariert bzw. Ich nehme an das Spiel soll mit einem fixen Geldwert beginnen?!

**Comment by CaribbeanMax** [comment]
hab die Main.java aktualisiert, sollte beides beheben
